### ISSUE TITLE
Arbre d'animation basique du personnage

### ISSUE THREAD

**Issue by JeeBayDay** [gladiawar/gladiawar#13]

**Comment by lecalvg** [comment]
Actuellement sur l'arbre d'animation. Fusion d'un FirstPersonneController et d'un modèle animé.

**Comment by Nalca** [comment]
C'en est où ? Tu peut nous montrer quelque chose (qui ne vient pas d'un tuto ?)

**Comment by lecalvg** [comment]
J'utilise l'anim tree d'un tuto pour le moment, j'essaye surtout de modifier le script du Controller.
