### ISSUE TITLE
"Missing scripts" au clone du dépôt

### ISSUE THREAD

**Issue by Nalca** [gladiawar/gladiawar#14]
La version en ligne ne marche pas. Les scripts ne sont pas 'retrouvés' par Unity.

Solution proposée (A appliquée par Dubreu_j puisqu'il est seul à avoir la bonne version) :
Edit -> Projects Settings -> Editor -> Version Control, sélectionner "Meta Files"
Et changer le .gitignore ensuite.

Assigné a dubreu_j car il est le seul a avoir la bonne version.

**Comment by JeeBayDay** [comment]
Le gitignore n'a pas a etre change. Les .meta ont ete ajoutes, appelez moi en cas de problemes sinon fermez le ticket.
