### ISSUE TITLE
Creation de la fenetre de login et d'inscription

### ISSUE THREAD

**Issue by JeeBayDay** [gladiawar/gladiawar#3]

**Comment by Nalca** [comment]
Il faut afficher les erreurs que l'on rencontre.
Genre le fait que le server ne réponde pas (normal, il n'existe pas encore).

**Comment by JeeBayDay** [comment]
Le serveur répond bel et bien vu que j'arrive m'inscrire et me connecter. C'est juste que c'est pas encore au point sur certaines choses lié au framework PHP mais je suis sur le coup.
