### ISSUE TITLE
Erreur de chargement d'une map

### ISSUE THREAD

**Issue by Nalca** [gladiawar/gladiawar#42]
En cas d'erreur de chargement d'une map (comme actuellement après un pull), il n'y a aucun message pour avertir le joueur de ce qui se passe.

**Comment by JeeBayDay** [comment]
Il ne s'agit pas d'un bug mais de l'utilisation du depot

**Comment by Nalca** [comment]
Je parle de la <b>gestion d'erreur</b> quand il n'y a pas de map.
Pas le fait que la map ne soit pas sur le répo.

**Comment by JeeBayDay** [comment]
il n'y a aucune gestion d'erreur a avoir puisque toutes les maps marquée dans un salon sont dans le package final et que une map par défaut est assignée au lancement d'une room
