### ISSUE TITLE
Creation du master serveur de jeu

### ISSUE THREAD

**Issue by JeeBayDay** [gladiawar/gladiawar#6]
Peut etre voir pour utiliser photon server

**Comment by Nalca** [comment]
Le master server est un executable a part (dont d'ailleurs les sources sont disponibles sur le site d'Unity).

Lien : http://docs.unity3d.com/Documentation/Components/net-MasterServerBuild.html

**Comment by Nalca** [comment]
Mise a jour :
J'ai ajouté des sources pour un master server en cpp (trouvé sur le site d'Unity).

Il marche, au moins sur Windows. Je n'ai pas tenté sur Linux.
Il faudra se connecter dessus (Par defaut, il se connecte sur un AUTRE server).
