### ISSUE TITLE
Creation de la structure d'un joueur

### ISSUE THREAD

**Issue by JeeBayDay** [gladiawar/gladiawar#8]
Systeme d'heritage a prevoir pour les differentes classes qui en decoulent

**Comment by Nalca** [comment]
On verra plus tard ça. (Car on va faire de la merde par inexpérience, c'est sur)

D'abord, communiquer en réseau. Ensuite faire fonctionner les animations puisqu'on dépend de ça.
Il faut juste ne pas oublier d'y penser plus tard.
